export const TRENDING_MOVIES = 'TRENDING_MOVIES';
export const POPULAR_MOVIES = 'POPULAR_MOVIES';

export const TRENDING_MOVIES_TAB = 'TRENDING_MOVIES_TAB';
export const POPULAR_MOVIES_TAB = 'POPULAR_MOVIES_TAB';